### ISSUE TITLE
wideq_state.json file not existing and not created

### ISSUE THREAD

**Issue by Artens** [majki09/domoticz_lg_thinq_plugin#7]
Expected behaviour:
preconditions
- GIT project cloned
- User on machine has access and write rights in plugin folder
run example.py 
-- country specification
-- language specification

URL copy/paste request comes up to obtain API key

Experienced behaviour:
Error code on line 268 of example.py
wideq_state.json is not present, i/o error

Solution:
- create a file wideq_state.json
-- i.e. 'touch wideq_state.json'
- edit file and add empty response brackets to make it a minimal JSON file
-- i.e. vi wideq_state.json, add {}, save and close

**Comment by majki09** [comment]
Hi @Artens !
Thanks for reporting this. There was a variable re-init missing that I forgot to put back into the *example* code.
It's OK now with https://github.com/majki09/domoticz_lg_thinq_plugin/commit/06ed7b4e6aa02f9f38c0390220c77ff29de797bc thus closing this issue.
