### ISSUE TITLE
Connect from belgium with google

### ISSUE THREAD

**Issue by cblomart** [majki09/domoticz_lg_thinq_plugin#8]
Hi,

When trying to setup the plugin i cannot get the first step to get the authentication from thinq.

As i registered my thinq account in belgium with google i do enter:

```bash
$ python3 example.py -c BE -l be-FR
```

When doing that the page doesn't show the google sign in... that i can re-enable by removing the ```show_thirdparty_login``` from the query or update it to contain ```GGL```

When trying to sign in with google, i am following trough confirming my mail and password and when redirected to lg... googles complains about an unauthorized URL :-(

Cédric

**Comment by majki09** [comment]
Hi @cblomart!

Unfortunately logging with Google is not supported and this is in installation manual:

> On first run, the script will ask you to log in with your LG account. Logging in with Google does not seem to work, but other methods (plain email & password, Facebook, and Amazon) do.

Can you log in with other way?
