### ISSUE TITLE
Set Target Temperature

### ISSUE THREAD

**Issue by fhennema** [majki09/domoticz_lg_thinq_plugin#9]
Hi,

Great plugin, thanks! I was wondering, is it possible to make a function which can set the target temperature from the Domoticz device? So, for example, it can be used in LUA scripting?

Thanks
Frank

**Comment by majki09** [comment]
Hi @fhennema.

Target temperature is just an another "device" for domoticz - you can do whatever you want with scripting. This is rather about domoticz scripting, not plugin itself:
`atstart
begin
end`

For LUA:
`commandArray = {}
if (devicechanged['MyDeviceName'] == 'On' and otherdevices['MyOtherDeviceName'] == 'Off') then
   commandArray['SetSetPoint:MySetPointIdx']='20.5'
end
return commandArray`

For [dzVents](https://www.domoticz.com/wiki/DzVents:_next_generation_Lua_scripting#Thermostat_set_point):
**Thermostat set point**
setPoint: Number.
updateSetPoint(setPoint):Function. Supports [command options](https://www.domoticz.com/wiki/DzVents:_next_generation_Lua_scripting#Command_options_.28delay.2C_duration.2C_event_triggering.29).

**Comment by fhennema** [comment]
This works! Thanks a lot.

Kind regards
Frank

**Comment by majki09** [comment]
That's awesome!
